version: "3.1"

services:
  web:
    hostname: api_bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
    volumes:
      - .:/app

  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5673:5672"
      - "15672:15672"

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery_task
    command: -A celery_task worker --loglevel=info
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: suspiron
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: api_bot

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080